Add List Years option to pcn laod
GPID-WB/pcn pull request #10
Opened 2020-03-03 21:29 UTC by davidlvargas

Saves in a local the available years and stop

2020-03-04 03:05 UTC, randrescastaneda requested changes
Hola David.

Muy buena la idea, pero por fa hazlo "clickable." algo así como, `pcn load, countr(IDN) year(select)` te despliega los años disponibles. Idealmente, cada click ejecuta `pcn load, countr(IDN) year(2018)` si ese es el año elegido y no `2018` solamente.... 

Llámame si tienes preguntas. 
Gracias. 
Andrés.

2020-03-04 03:11 UTC, davidlvargas commented
Dale haré eso. Sin embargo la opción cómo está, la pensé para responder a algo que necesitaba Christoph. Él quiere tener los años que hay para cada país como un local con el cual el pueda trabajar. Tal vez podríamos hacer dos opciones (o incluso un módulo) que sea con explore y de info sobre lo que hay el los folders

2020-03-05 19:41 UTC, randrescastaneda commented
Me parece una muy buena idea. Procede con tu idea. 
Gracias.

2020-06-23 22:38 UTC, randrescastaneda commented
HOla David. 

Esto es un poco viejo y no recuerdo si ya está terminado. Si no lo está, no hay problema. Solo quiero saber si se puede incorporar o no. 

Gracias!

2020-06-23 23:15 UTC, davidlvargas commented
Hola Andres,

No, se me había pasado por completo. No debería tomar mucho, en estos días
te hago un pull request con eso.

Un abrazo
DV

Le mar. 23 juin 2020 à 18:38, R.Andrés Castañeda <notifications@github.com>
a écrit :

> HOla David.
>
> Esto es un poco viejo y no recuerdo si ya está terminado. Si no lo está,
> no hay problema. Solo quiero saber si se puede incorporar o no.
>
> Gracias!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PovcalNet-Team/pcn/pull/10#issuecomment-648464577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMY2NO472FYUQIOY3PBS5KLRYEVH3ANCNFSM4LATTBLA>
> .
>

2020-06-24 14:23 UTC, davidlvargas commented
Hola Andres, 

La funcionalidad básica de tener un local con años ya estaba hecha. Hice un rebase del branch y ya solucione los conflictos. Ya puedes hacer el merge, sin lío.

Me cuentas cualquier cosa
Un abrazo

2020-06-24 19:16 UTC, merged

2020-06-24 19:17 UTC, randrescastaneda commented
Buenisimo. Mil gracias!